// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/signal.proto

package signal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignalType 信令类型
type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNKNOWN    SignalType = 0
	SignalType_SIGNAL_TYPE_OFFER      SignalType = 1 // 连接请求
	SignalType_SIGNAL_TYPE_ANSWER     SignalType = 2 // 连接响应
	SignalType_SIGNAL_TYPE_CANDIDATE  SignalType = 3 // ICE 候选（端点信息）
	SignalType_SIGNAL_TYPE_PUNCH      SignalType = 4 // 打洞请求
	SignalType_SIGNAL_TYPE_PUNCH_ACK  SignalType = 5 // 打洞确认
	SignalType_SIGNAL_TYPE_KEEPALIVE  SignalType = 6 // 保活
	SignalType_SIGNAL_TYPE_DISCONNECT SignalType = 7 // 断开连接
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "SIGNAL_TYPE_UNKNOWN",
		1: "SIGNAL_TYPE_OFFER",
		2: "SIGNAL_TYPE_ANSWER",
		3: "SIGNAL_TYPE_CANDIDATE",
		4: "SIGNAL_TYPE_PUNCH",
		5: "SIGNAL_TYPE_PUNCH_ACK",
		6: "SIGNAL_TYPE_KEEPALIVE",
		7: "SIGNAL_TYPE_DISCONNECT",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNKNOWN":    0,
		"SIGNAL_TYPE_OFFER":      1,
		"SIGNAL_TYPE_ANSWER":     2,
		"SIGNAL_TYPE_CANDIDATE":  3,
		"SIGNAL_TYPE_PUNCH":      4,
		"SIGNAL_TYPE_PUNCH_ACK":  5,
		"SIGNAL_TYPE_KEEPALIVE":  6,
		"SIGNAL_TYPE_DISCONNECT": 7,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_signal_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_api_proto_signal_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{0}
}

// EndpointType 端点类型
type EndpointType int32

const (
	EndpointType_ENDPOINT_TYPE_UNKNOWN EndpointType = 0
	EndpointType_ENDPOINT_TYPE_LOCAL   EndpointType = 1 // 本地地址
	EndpointType_ENDPOINT_TYPE_STUN    EndpointType = 2 // STUN 探测的公网地址
	EndpointType_ENDPOINT_TYPE_RELAY   EndpointType = 3 // 中继地址
)

// Enum value maps for EndpointType.
var (
	EndpointType_name = map[int32]string{
		0: "ENDPOINT_TYPE_UNKNOWN",
		1: "ENDPOINT_TYPE_LOCAL",
		2: "ENDPOINT_TYPE_STUN",
		3: "ENDPOINT_TYPE_RELAY",
	}
	EndpointType_value = map[string]int32{
		"ENDPOINT_TYPE_UNKNOWN": 0,
		"ENDPOINT_TYPE_LOCAL":   1,
		"ENDPOINT_TYPE_STUN":    2,
		"ENDPOINT_TYPE_RELAY":   3,
	}
)

func (x EndpointType) Enum() *EndpointType {
	p := new(EndpointType)
	*p = x
	return p
}

func (x EndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_signal_proto_enumTypes[1].Descriptor()
}

func (EndpointType) Type() protoreflect.EnumType {
	return &file_api_proto_signal_proto_enumTypes[1]
}

func (x EndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointType.Descriptor instead.
func (EndpointType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{1}
}

// NATType NAT 类型
type NATType int32

const (
	NATType_NAT_TYPE_UNKNOWN         NATType = 0
	NATType_NAT_TYPE_NONE            NATType = 1
	NATType_NAT_TYPE_FULL_CONE       NATType = 2
	NATType_NAT_TYPE_RESTRICTED      NATType = 3
	NATType_NAT_TYPE_PORT_RESTRICTED NATType = 4
	NATType_NAT_TYPE_SYMMETRIC       NATType = 5
)

// Enum value maps for NATType.
var (
	NATType_name = map[int32]string{
		0: "NAT_TYPE_UNKNOWN",
		1: "NAT_TYPE_NONE",
		2: "NAT_TYPE_FULL_CONE",
		3: "NAT_TYPE_RESTRICTED",
		4: "NAT_TYPE_PORT_RESTRICTED",
		5: "NAT_TYPE_SYMMETRIC",
	}
	NATType_value = map[string]int32{
		"NAT_TYPE_UNKNOWN":         0,
		"NAT_TYPE_NONE":            1,
		"NAT_TYPE_FULL_CONE":       2,
		"NAT_TYPE_RESTRICTED":      3,
		"NAT_TYPE_PORT_RESTRICTED": 4,
		"NAT_TYPE_SYMMETRIC":       5,
	}
)

func (x NATType) Enum() *NATType {
	p := new(NATType)
	*p = x
	return p
}

func (x NATType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NATType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_signal_proto_enumTypes[2].Descriptor()
}

func (NATType) Type() protoreflect.EnumType {
	return &file_api_proto_signal_proto_enumTypes[2]
}

func (x NATType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NATType.Descriptor instead.
func (NATType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{2}
}

// SignalMessage 信令消息
type SignalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDeviceId  string                 `protobuf:"bytes,1,opt,name=from_device_id,json=fromDeviceId,proto3" json:"from_device_id,omitempty"` // 发送方设备 ID
	ToDeviceId    string                 `protobuf:"bytes,2,opt,name=to_device_id,json=toDeviceId,proto3" json:"to_device_id,omitempty"`       // 接收方设备 ID
	Type          SignalType             `protobuf:"varint,3,opt,name=type,proto3,enum=api.signal.SignalType" json:"type,omitempty"`           // 信令类型
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                 // 信令载荷
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                            // 时间戳（毫秒）
	MessageId     string                 `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`            // 消息 ID（用于去重和确认）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_api_proto_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalMessage) GetFromDeviceId() string {
	if x != nil {
		return x.FromDeviceId
	}
	return ""
}

func (x *SignalMessage) GetToDeviceId() string {
	if x != nil {
		return x.ToDeviceId
	}
	return ""
}

func (x *SignalMessage) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_SIGNAL_TYPE_UNKNOWN
}

func (x *SignalMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SignalMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// OfferPayload 连接请求载荷
type OfferPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`     // 发起方 WireGuard 公钥
	ListenPort    int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"` // 发起方 WireGuard 监听端口
	Endpoints     []*Endpoint            `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`                      // 发起方可能的端点列表
	NatInfo       *NATInfo               `protobuf:"bytes,4,opt,name=nat_info,json=natInfo,proto3" json:"nat_info,omitempty"`           // 发起方 NAT 信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferPayload) Reset() {
	*x = OfferPayload{}
	mi := &file_api_proto_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferPayload) ProtoMessage() {}

func (x *OfferPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferPayload.ProtoReflect.Descriptor instead.
func (*OfferPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{1}
}

func (x *OfferPayload) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *OfferPayload) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *OfferPayload) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *OfferPayload) GetNatInfo() *NATInfo {
	if x != nil {
		return x.NatInfo
	}
	return nil
}

// AnswerPayload 连接响应载荷
type AnswerPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`          // 响应方 WireGuard 公钥
	ListenPort    int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`      // 响应方 WireGuard 监听端口
	Endpoints     []*Endpoint            `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`                           // 响应方可能的端点列表
	NatInfo       *NATInfo               `protobuf:"bytes,4,opt,name=nat_info,json=natInfo,proto3" json:"nat_info,omitempty"`                // 响应方 NAT 信息
	Accepted      bool                   `protobuf:"varint,5,opt,name=accepted,proto3" json:"accepted,omitempty"`                            // 是否接受连接
	RejectReason  string                 `protobuf:"bytes,6,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 拒绝原因（如不接受）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerPayload) Reset() {
	*x = AnswerPayload{}
	mi := &file_api_proto_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerPayload) ProtoMessage() {}

func (x *AnswerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerPayload.ProtoReflect.Descriptor instead.
func (*AnswerPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{2}
}

func (x *AnswerPayload) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AnswerPayload) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *AnswerPayload) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *AnswerPayload) GetNatInfo() *NATInfo {
	if x != nil {
		return x.NatInfo
	}
	return nil
}

func (x *AnswerPayload) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AnswerPayload) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// Endpoint 端点信息
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                         // IP:Port
	Type          EndpointType           `protobuf:"varint,2,opt,name=type,proto3,enum=api.signal.EndpointType" json:"type,omitempty"` // 端点类型
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                      // 优先级（越高越优先）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_proto_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Endpoint) GetType() EndpointType {
	if x != nil {
		return x.Type
	}
	return EndpointType_ENDPOINT_TYPE_UNKNOWN
}

func (x *Endpoint) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// CandidatePayload ICE 候选载荷
type CandidatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"` // 新发现的端点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidatePayload) Reset() {
	*x = CandidatePayload{}
	mi := &file_api_proto_signal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidatePayload) ProtoMessage() {}

func (x *CandidatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidatePayload.ProtoReflect.Descriptor instead.
func (*CandidatePayload) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{4}
}

func (x *CandidatePayload) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// PunchPayload 打洞请求载荷
type PunchPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAddress   string                 `protobuf:"bytes,1,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`          // 目标地址（对方提供的端点）
	PunchCount      int32                  `protobuf:"varint,2,opt,name=punch_count,json=punchCount,proto3" json:"punch_count,omitempty"`                  // 打洞尝试次数
	PunchIntervalMs int64                  `protobuf:"varint,3,opt,name=punch_interval_ms,json=punchIntervalMs,proto3" json:"punch_interval_ms,omitempty"` // 打洞间隔（毫秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PunchPayload) Reset() {
	*x = PunchPayload{}
	mi := &file_api_proto_signal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchPayload) ProtoMessage() {}

func (x *PunchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchPayload.ProtoReflect.Descriptor instead.
func (*PunchPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{5}
}

func (x *PunchPayload) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *PunchPayload) GetPunchCount() int32 {
	if x != nil {
		return x.PunchCount
	}
	return 0
}

func (x *PunchPayload) GetPunchIntervalMs() int64 {
	if x != nil {
		return x.PunchIntervalMs
	}
	return 0
}

// PunchAckPayload 打洞确认载荷
type PunchAckPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                             // 是否成功
	ConnectedEndpoint string                 `protobuf:"bytes,2,opt,name=connected_endpoint,json=connectedEndpoint,proto3" json:"connected_endpoint,omitempty"` // 成功连接的端点
	RttMs             int64                  `protobuf:"varint,3,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`                                    // 往返时延（毫秒）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PunchAckPayload) Reset() {
	*x = PunchAckPayload{}
	mi := &file_api_proto_signal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchAckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchAckPayload) ProtoMessage() {}

func (x *PunchAckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchAckPayload.ProtoReflect.Descriptor instead.
func (*PunchAckPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{6}
}

func (x *PunchAckPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PunchAckPayload) GetConnectedEndpoint() string {
	if x != nil {
		return x.ConnectedEndpoint
	}
	return ""
}

func (x *PunchAckPayload) GetRttMs() int64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

// NATInfo NAT 信息（与 management.proto 保持一致）
type NATInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NATType                `protobuf:"varint,1,opt,name=type,proto3,enum=api.signal.NATType" json:"type,omitempty"`
	PublicAddr    string                 `protobuf:"bytes,2,opt,name=public_addr,json=publicAddr,proto3" json:"public_addr,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,3,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NATInfo) Reset() {
	*x = NATInfo{}
	mi := &file_api_proto_signal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NATInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NATInfo) ProtoMessage() {}

func (x *NATInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NATInfo.ProtoReflect.Descriptor instead.
func (*NATInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_proto_rawDescGZIP(), []int{7}
}

func (x *NATInfo) GetType() NATType {
	if x != nil {
		return x.Type
	}
	return NATType_NAT_TYPE_UNKNOWN
}

func (x *NATInfo) GetPublicAddr() string {
	if x != nil {
		return x.PublicAddr
	}
	return ""
}

func (x *NATInfo) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

var File_api_proto_signal_proto protoreflect.FileDescriptor

const file_api_proto_signal_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/signal.proto\x12\n" +
	"api.signal\"\xda\x01\n" +
	"\rSignalMessage\x12$\n" +
	"\x0efrom_device_id\x18\x01 \x01(\tR\ffromDeviceId\x12 \n" +
	"\fto_device_id\x18\x02 \x01(\tR\n" +
	"toDeviceId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.api.signal.SignalTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x06 \x01(\tR\tmessageId\"\xb2\x01\n" +
	"\fOfferPayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x122\n" +
	"\tendpoints\x18\x03 \x03(\v2\x14.api.signal.EndpointR\tendpoints\x12.\n" +
	"\bnat_info\x18\x04 \x01(\v2\x13.api.signal.NATInfoR\anatInfo\"\xf4\x01\n" +
	"\rAnswerPayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x122\n" +
	"\tendpoints\x18\x03 \x03(\v2\x14.api.signal.EndpointR\tendpoints\x12.\n" +
	"\bnat_info\x18\x04 \x01(\v2\x13.api.signal.NATInfoR\anatInfo\x12\x1a\n" +
	"\baccepted\x18\x05 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x06 \x01(\tR\frejectReason\"n\n" +
	"\bEndpoint\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.api.signal.EndpointTypeR\x04type\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"F\n" +
	"\x10CandidatePayload\x122\n" +
	"\tendpoints\x18\x01 \x03(\v2\x14.api.signal.EndpointR\tendpoints\"\x82\x01\n" +
	"\fPunchPayload\x12%\n" +
	"\x0etarget_address\x18\x01 \x01(\tR\rtargetAddress\x12\x1f\n" +
	"\vpunch_count\x18\x02 \x01(\x05R\n" +
	"punchCount\x12*\n" +
	"\x11punch_interval_ms\x18\x03 \x01(\x03R\x0fpunchIntervalMs\"q\n" +
	"\x0fPunchAckPayload\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x12connected_endpoint\x18\x02 \x01(\tR\x11connectedEndpoint\x12\x15\n" +
	"\x06rtt_ms\x18\x03 \x01(\x03R\x05rttMs\"r\n" +
	"\aNATInfo\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.api.signal.NATTypeR\x04type\x12\x1f\n" +
	"\vpublic_addr\x18\x02 \x01(\tR\n" +
	"publicAddr\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x03 \x01(\tR\tlocalAddr*\xd8\x01\n" +
	"\n" +
	"SignalType\x12\x17\n" +
	"\x13SIGNAL_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11SIGNAL_TYPE_OFFER\x10\x01\x12\x16\n" +
	"\x12SIGNAL_TYPE_ANSWER\x10\x02\x12\x19\n" +
	"\x15SIGNAL_TYPE_CANDIDATE\x10\x03\x12\x15\n" +
	"\x11SIGNAL_TYPE_PUNCH\x10\x04\x12\x19\n" +
	"\x15SIGNAL_TYPE_PUNCH_ACK\x10\x05\x12\x19\n" +
	"\x15SIGNAL_TYPE_KEEPALIVE\x10\x06\x12\x1a\n" +
	"\x16SIGNAL_TYPE_DISCONNECT\x10\a*s\n" +
	"\fEndpointType\x12\x19\n" +
	"\x15ENDPOINT_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13ENDPOINT_TYPE_LOCAL\x10\x01\x12\x16\n" +
	"\x12ENDPOINT_TYPE_STUN\x10\x02\x12\x17\n" +
	"\x13ENDPOINT_TYPE_RELAY\x10\x03*\x99\x01\n" +
	"\aNATType\x12\x14\n" +
	"\x10NAT_TYPE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rNAT_TYPE_NONE\x10\x01\x12\x16\n" +
	"\x12NAT_TYPE_FULL_CONE\x10\x02\x12\x17\n" +
	"\x13NAT_TYPE_RESTRICTED\x10\x03\x12\x1c\n" +
	"\x18NAT_TYPE_PORT_RESTRICTED\x10\x04\x12\x16\n" +
	"\x12NAT_TYPE_SYMMETRIC\x10\x052T\n" +
	"\rSignalService\x12C\n" +
	"\aConnect\x12\x19.api.signal.SignalMessage\x1a\x19.api.signal.SignalMessage(\x010\x01B&Z$github.com/example/go-vpc/api/signalb\x06proto3"

var (
	file_api_proto_signal_proto_rawDescOnce sync.Once
	file_api_proto_signal_proto_rawDescData []byte
)

func file_api_proto_signal_proto_rawDescGZIP() []byte {
	file_api_proto_signal_proto_rawDescOnce.Do(func() {
		file_api_proto_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_signal_proto_rawDesc), len(file_api_proto_signal_proto_rawDesc)))
	})
	return file_api_proto_signal_proto_rawDescData
}

var file_api_proto_signal_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_signal_proto_goTypes = []any{
	(SignalType)(0),          // 0: api.signal.SignalType
	(EndpointType)(0),        // 1: api.signal.EndpointType
	(NATType)(0),             // 2: api.signal.NATType
	(*SignalMessage)(nil),    // 3: api.signal.SignalMessage
	(*OfferPayload)(nil),     // 4: api.signal.OfferPayload
	(*AnswerPayload)(nil),    // 5: api.signal.AnswerPayload
	(*Endpoint)(nil),         // 6: api.signal.Endpoint
	(*CandidatePayload)(nil), // 7: api.signal.CandidatePayload
	(*PunchPayload)(nil),     // 8: api.signal.PunchPayload
	(*PunchAckPayload)(nil),  // 9: api.signal.PunchAckPayload
	(*NATInfo)(nil),          // 10: api.signal.NATInfo
}
var file_api_proto_signal_proto_depIdxs = []int32{
	0,  // 0: api.signal.SignalMessage.type:type_name -> api.signal.SignalType
	6,  // 1: api.signal.OfferPayload.endpoints:type_name -> api.signal.Endpoint
	10, // 2: api.signal.OfferPayload.nat_info:type_name -> api.signal.NATInfo
	6,  // 3: api.signal.AnswerPayload.endpoints:type_name -> api.signal.Endpoint
	10, // 4: api.signal.AnswerPayload.nat_info:type_name -> api.signal.NATInfo
	1,  // 5: api.signal.Endpoint.type:type_name -> api.signal.EndpointType
	6,  // 6: api.signal.CandidatePayload.endpoints:type_name -> api.signal.Endpoint
	2,  // 7: api.signal.NATInfo.type:type_name -> api.signal.NATType
	3,  // 8: api.signal.SignalService.Connect:input_type -> api.signal.SignalMessage
	3,  // 9: api.signal.SignalService.Connect:output_type -> api.signal.SignalMessage
	9,  // [9:10] is the sub-list for method output_type
	8,  // [8:9] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_signal_proto_init() }
func file_api_proto_signal_proto_init() {
	if File_api_proto_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_signal_proto_rawDesc), len(file_api_proto_signal_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_signal_proto_goTypes,
		DependencyIndexes: file_api_proto_signal_proto_depIdxs,
		EnumInfos:         file_api_proto_signal_proto_enumTypes,
		MessageInfos:      file_api_proto_signal_proto_msgTypes,
	}.Build()
	File_api_proto_signal_proto = out.File
	file_api_proto_signal_proto_goTypes = nil
	file_api_proto_signal_proto_depIdxs = nil
}
