// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/management.proto

package management

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NATType NAT 类型
type NATType int32

const (
	NATType_NAT_TYPE_UNKNOWN         NATType = 0
	NATType_NAT_TYPE_NONE            NATType = 1 // 无 NAT（公网 IP）
	NATType_NAT_TYPE_FULL_CONE       NATType = 2 // 全锥形
	NATType_NAT_TYPE_RESTRICTED      NATType = 3 // 受限锥形
	NATType_NAT_TYPE_PORT_RESTRICTED NATType = 4 // 端口受限锥形
	NATType_NAT_TYPE_SYMMETRIC       NATType = 5 // 对称型
)

// Enum value maps for NATType.
var (
	NATType_name = map[int32]string{
		0: "NAT_TYPE_UNKNOWN",
		1: "NAT_TYPE_NONE",
		2: "NAT_TYPE_FULL_CONE",
		3: "NAT_TYPE_RESTRICTED",
		4: "NAT_TYPE_PORT_RESTRICTED",
		5: "NAT_TYPE_SYMMETRIC",
	}
	NATType_value = map[string]int32{
		"NAT_TYPE_UNKNOWN":         0,
		"NAT_TYPE_NONE":            1,
		"NAT_TYPE_FULL_CONE":       2,
		"NAT_TYPE_RESTRICTED":      3,
		"NAT_TYPE_PORT_RESTRICTED": 4,
		"NAT_TYPE_SYMMETRIC":       5,
	}
)

func (x NATType) Enum() *NATType {
	p := new(NATType)
	*p = x
	return p
}

func (x NATType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NATType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_management_proto_enumTypes[0].Descriptor()
}

func (NATType) Type() protoreflect.EnumType {
	return &file_api_proto_management_proto_enumTypes[0]
}

func (x NATType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NATType.Descriptor instead.
func (NATType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{0}
}

// CommandType 命令类型
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNKNOWN      CommandType = 0
	CommandType_COMMAND_TYPE_UPDATE_PEERS CommandType = 1 // 更新 Peer 列表
	CommandType_COMMAND_TYPE_RECONNECT    CommandType = 2 // 重新连接
	CommandType_COMMAND_TYPE_UPGRADE      CommandType = 3 // 升级 Agent
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNKNOWN",
		1: "COMMAND_TYPE_UPDATE_PEERS",
		2: "COMMAND_TYPE_RECONNECT",
		3: "COMMAND_TYPE_UPGRADE",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNKNOWN":      0,
		"COMMAND_TYPE_UPDATE_PEERS": 1,
		"COMMAND_TYPE_RECONNECT":    2,
		"COMMAND_TYPE_UPGRADE":      3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_management_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_api_proto_management_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{1}
}

// PeerUpdateType Peer 更新类型
type PeerUpdateType int32

const (
	PeerUpdateType_PEER_UPDATE_TYPE_UNKNOWN PeerUpdateType = 0
	PeerUpdateType_PEER_UPDATE_TYPE_ADD     PeerUpdateType = 1 // 添加 Peer
	PeerUpdateType_PEER_UPDATE_TYPE_REMOVE  PeerUpdateType = 2 // 移除 Peer
	PeerUpdateType_PEER_UPDATE_TYPE_UPDATE  PeerUpdateType = 3 // 更新 Peer
)

// Enum value maps for PeerUpdateType.
var (
	PeerUpdateType_name = map[int32]string{
		0: "PEER_UPDATE_TYPE_UNKNOWN",
		1: "PEER_UPDATE_TYPE_ADD",
		2: "PEER_UPDATE_TYPE_REMOVE",
		3: "PEER_UPDATE_TYPE_UPDATE",
	}
	PeerUpdateType_value = map[string]int32{
		"PEER_UPDATE_TYPE_UNKNOWN": 0,
		"PEER_UPDATE_TYPE_ADD":     1,
		"PEER_UPDATE_TYPE_REMOVE":  2,
		"PEER_UPDATE_TYPE_UPDATE":  3,
	}
)

func (x PeerUpdateType) Enum() *PeerUpdateType {
	p := new(PeerUpdateType)
	*p = x
	return p
}

func (x PeerUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_management_proto_enumTypes[2].Descriptor()
}

func (PeerUpdateType) Type() protoreflect.EnumType {
	return &file_api_proto_management_proto_enumTypes[2]
}

func (x PeerUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerUpdateType.Descriptor instead.
func (PeerUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{2}
}

// RegisterRequest 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // 设备唯一标识
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`    // WireGuard 公钥（Base64）
	Fingerprint   string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                 // 设备指纹
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"` // 设备信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RegisterRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

// DeviceInfo 设备信息
type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"` // 主机名
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`             // 操作系统
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`         // CPU 架构
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`   // Agent 版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_api_proto_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DeviceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// RegisterResponse 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedVip   string                 `protobuf:"bytes,3,opt,name=assigned_vip,json=assignedVip,proto3" json:"assigned_vip,omitempty"` // 分配的 VIP 地址
	VipPrefix     int32                  `protobuf:"varint,4,opt,name=vip_prefix,json=vipPrefix,proto3" json:"vip_prefix,omitempty"`      // VIP 网段前缀长度
	NetworkId     string                 `protobuf:"bytes,5,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`       // 所属网络 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAssignedVip() string {
	if x != nil {
		return x.AssignedVip
	}
	return ""
}

func (x *RegisterResponse) GetVipPrefix() int32 {
	if x != nil {
		return x.VipPrefix
	}
	return 0
}

func (x *RegisterResponse) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // Unix 时间戳（毫秒）
	NatInfo       *NATInfo               `protobuf:"bytes,3,opt,name=nat_info,json=natInfo,proto3" json:"nat_info,omitempty"` // NAT 信息（可选，变化时上报）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetNatInfo() *NATInfo {
	if x != nil {
		return x.NatInfo
	}
	return nil
}

// NATInfo NAT 信息
type NATInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NATType                `protobuf:"varint,1,opt,name=type,proto3,enum=api.management.NATType" json:"type,omitempty"`
	PublicAddr    string                 `protobuf:"bytes,2,opt,name=public_addr,json=publicAddr,proto3" json:"public_addr,omitempty"` // 公网地址 IP:Port
	LocalAddr     string                 `protobuf:"bytes,3,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`    // 本地地址 IP:Port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NATInfo) Reset() {
	*x = NATInfo{}
	mi := &file_api_proto_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NATInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NATInfo) ProtoMessage() {}

func (x *NATInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NATInfo.ProtoReflect.Descriptor instead.
func (*NATInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{4}
}

func (x *NATInfo) GetType() NATType {
	if x != nil {
		return x.Type
	}
	return NATType_NAT_TYPE_UNKNOWN
}

func (x *NATInfo) GetPublicAddr() string {
	if x != nil {
		return x.PublicAddr
	}
	return ""
}

func (x *NATInfo) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务器时间
	Commands      []*Command             `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`                        // 待执行命令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

// Command 服务端下发的命令
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=api.management.CommandType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 命令载荷（JSON 或 Protobuf）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_proto_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{6}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNKNOWN
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// GetNetworkConfigRequest 获取网络配置请求
type GetNetworkConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkConfigRequest) Reset() {
	*x = GetNetworkConfigRequest{}
	mi := &file_api_proto_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkConfigRequest) ProtoMessage() {}

func (x *GetNetworkConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkConfigRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{7}
}

func (x *GetNetworkConfigRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetNetworkConfigRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

// NetworkConfig 网络配置
type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NetworkCidr   string                 `protobuf:"bytes,2,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"` // 网络 CIDR，如 10.0.0.0/8
	Mtu           int32                  `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`                                   // MTU 大小
	DnsServers    []string               `protobuf:"bytes,4,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`    // DNS 服务器列表
	Routes        []*RouteConfig         `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`                              // 路由配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_api_proto_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkConfig) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *NetworkConfig) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *NetworkConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkConfig) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *NetworkConfig) GetRoutes() []*RouteConfig {
	if x != nil {
		return x.Routes
	}
	return nil
}

// RouteConfig 路由配置
type RouteConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"` // 目标网段 CIDR
	Via           string                 `protobuf:"bytes,2,opt,name=via,proto3" json:"via,omitempty"`                 // 下一跳（VIP 或 device_id）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteConfig) Reset() {
	*x = RouteConfig{}
	mi := &file_api_proto_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfig) ProtoMessage() {}

func (x *RouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfig.ProtoReflect.Descriptor instead.
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{9}
}

func (x *RouteConfig) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteConfig) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

// SyncPeersRequest 同步 Peer 请求
type SyncPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPeersRequest) Reset() {
	*x = SyncPeersRequest{}
	mi := &file_api_proto_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPeersRequest) ProtoMessage() {}

func (x *SyncPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPeersRequest.ProtoReflect.Descriptor instead.
func (*SyncPeersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{10}
}

func (x *SyncPeersRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SyncPeersRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

// PeerUpdate Peer 更新
type PeerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PeerUpdateType         `protobuf:"varint,1,opt,name=type,proto3,enum=api.management.PeerUpdateType" json:"type,omitempty"`
	Peer          *PeerInfo              `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_api_proto_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{11}
}

func (x *PeerUpdate) GetType() PeerUpdateType {
	if x != nil {
		return x.Type
	}
	return PeerUpdateType_PEER_UPDATE_TYPE_UNKNOWN
}

func (x *PeerUpdate) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

// PeerInfo Peer 信息
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // WireGuard 公钥
	Vip           string                 `protobuf:"bytes,3,opt,name=vip,proto3" json:"vip,omitempty"`                              // VIP 地址
	Endpoints     []string               `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`                  // 可能的端点列表
	NatType       NATType                `protobuf:"varint,5,opt,name=nat_type,json=natType,proto3,enum=api.management.NATType" json:"nat_type,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,6,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"` // 允许的 IP 范围
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_api_proto_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_management_proto_rawDescGZIP(), []int{12}
}

func (x *PeerInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerInfo) GetVip() string {
	if x != nil {
		return x.Vip
	}
	return ""
}

func (x *PeerInfo) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *PeerInfo) GetNatType() NATType {
	if x != nil {
		return x.NatType
	}
	return NATType_NAT_TYPE_UNKNOWN
}

func (x *PeerInfo) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

var File_api_proto_management_proto protoreflect.FileDescriptor

const file_api_proto_management_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/management.proto\x12\x0eapi.management\"\xac\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\x12;\n" +
	"\vdevice_info\x18\x04 \x01(\v2\x1a.api.management.DeviceInfoR\n" +
	"deviceInfo\"f\n" +
	"\n" +
	"DeviceInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xa7\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fassigned_vip\x18\x03 \x01(\tR\vassignedVip\x12\x1d\n" +
	"\n" +
	"vip_prefix\x18\x04 \x01(\x05R\tvipPrefix\x12\x1d\n" +
	"\n" +
	"network_id\x18\x05 \x01(\tR\tnetworkId\"\x81\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x122\n" +
	"\bnat_info\x18\x03 \x01(\v2\x17.api.management.NATInfoR\anatInfo\"v\n" +
	"\aNATInfo\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.api.management.NATTypeR\x04type\x12\x1f\n" +
	"\vpublic_addr\x18\x02 \x01(\tR\n" +
	"publicAddr\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x03 \x01(\tR\tlocalAddr\"i\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\x123\n" +
	"\bcommands\x18\x02 \x03(\v2\x17.api.management.CommandR\bcommands\"T\n" +
	"\aCommand\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.api.management.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"U\n" +
	"\x17GetNetworkConfigRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\"\xb9\x01\n" +
	"\rNetworkConfig\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12!\n" +
	"\fnetwork_cidr\x18\x02 \x01(\tR\vnetworkCidr\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\x05R\x03mtu\x12\x1f\n" +
	"\vdns_servers\x18\x04 \x03(\tR\n" +
	"dnsServers\x123\n" +
	"\x06routes\x18\x05 \x03(\v2\x1b.api.management.RouteConfigR\x06routes\"A\n" +
	"\vRouteConfig\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x10\n" +
	"\x03via\x18\x02 \x01(\tR\x03via\"N\n" +
	"\x10SyncPeersRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\"n\n" +
	"\n" +
	"PeerUpdate\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.api.management.PeerUpdateTypeR\x04type\x12,\n" +
	"\x04peer\x18\x02 \x01(\v2\x18.api.management.PeerInfoR\x04peer\"\xcb\x01\n" +
	"\bPeerInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x10\n" +
	"\x03vip\x18\x03 \x01(\tR\x03vip\x12\x1c\n" +
	"\tendpoints\x18\x04 \x03(\tR\tendpoints\x122\n" +
	"\bnat_type\x18\x05 \x01(\x0e2\x17.api.management.NATTypeR\anatType\x12\x1f\n" +
	"\vallowed_ips\x18\x06 \x03(\tR\n" +
	"allowedIps*\x99\x01\n" +
	"\aNATType\x12\x14\n" +
	"\x10NAT_TYPE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rNAT_TYPE_NONE\x10\x01\x12\x16\n" +
	"\x12NAT_TYPE_FULL_CONE\x10\x02\x12\x17\n" +
	"\x13NAT_TYPE_RESTRICTED\x10\x03\x12\x1c\n" +
	"\x18NAT_TYPE_PORT_RESTRICTED\x10\x04\x12\x16\n" +
	"\x12NAT_TYPE_SYMMETRIC\x10\x05*|\n" +
	"\vCommandType\x12\x18\n" +
	"\x14COMMAND_TYPE_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19COMMAND_TYPE_UPDATE_PEERS\x10\x01\x12\x1a\n" +
	"\x16COMMAND_TYPE_RECONNECT\x10\x02\x12\x18\n" +
	"\x14COMMAND_TYPE_UPGRADE\x10\x03*\x82\x01\n" +
	"\x0ePeerUpdateType\x12\x1c\n" +
	"\x18PEER_UPDATE_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14PEER_UPDATE_TYPE_ADD\x10\x01\x12\x1b\n" +
	"\x17PEER_UPDATE_TYPE_REMOVE\x10\x02\x12\x1b\n" +
	"\x17PEER_UPDATE_TYPE_UPDATE\x10\x032\xe1\x02\n" +
	"\x11ManagementService\x12M\n" +
	"\bRegister\x12\x1f.api.management.RegisterRequest\x1a .api.management.RegisterResponse\x12T\n" +
	"\tHeartbeat\x12 .api.management.HeartbeatRequest\x1a!.api.management.HeartbeatResponse(\x010\x01\x12Z\n" +
	"\x10GetNetworkConfig\x12'.api.management.GetNetworkConfigRequest\x1a\x1d.api.management.NetworkConfig\x12K\n" +
	"\tSyncPeers\x12 .api.management.SyncPeersRequest\x1a\x1a.api.management.PeerUpdate0\x01B*Z(github.com/example/go-vpc/api/managementb\x06proto3"

var (
	file_api_proto_management_proto_rawDescOnce sync.Once
	file_api_proto_management_proto_rawDescData []byte
)

func file_api_proto_management_proto_rawDescGZIP() []byte {
	file_api_proto_management_proto_rawDescOnce.Do(func() {
		file_api_proto_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_management_proto_rawDesc), len(file_api_proto_management_proto_rawDesc)))
	})
	return file_api_proto_management_proto_rawDescData
}

var file_api_proto_management_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_management_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_management_proto_goTypes = []any{
	(NATType)(0),                    // 0: api.management.NATType
	(CommandType)(0),                // 1: api.management.CommandType
	(PeerUpdateType)(0),             // 2: api.management.PeerUpdateType
	(*RegisterRequest)(nil),         // 3: api.management.RegisterRequest
	(*DeviceInfo)(nil),              // 4: api.management.DeviceInfo
	(*RegisterResponse)(nil),        // 5: api.management.RegisterResponse
	(*HeartbeatRequest)(nil),        // 6: api.management.HeartbeatRequest
	(*NATInfo)(nil),                 // 7: api.management.NATInfo
	(*HeartbeatResponse)(nil),       // 8: api.management.HeartbeatResponse
	(*Command)(nil),                 // 9: api.management.Command
	(*GetNetworkConfigRequest)(nil), // 10: api.management.GetNetworkConfigRequest
	(*NetworkConfig)(nil),           // 11: api.management.NetworkConfig
	(*RouteConfig)(nil),             // 12: api.management.RouteConfig
	(*SyncPeersRequest)(nil),        // 13: api.management.SyncPeersRequest
	(*PeerUpdate)(nil),              // 14: api.management.PeerUpdate
	(*PeerInfo)(nil),                // 15: api.management.PeerInfo
}
var file_api_proto_management_proto_depIdxs = []int32{
	4,  // 0: api.management.RegisterRequest.device_info:type_name -> api.management.DeviceInfo
	7,  // 1: api.management.HeartbeatRequest.nat_info:type_name -> api.management.NATInfo
	0,  // 2: api.management.NATInfo.type:type_name -> api.management.NATType
	9,  // 3: api.management.HeartbeatResponse.commands:type_name -> api.management.Command
	1,  // 4: api.management.Command.type:type_name -> api.management.CommandType
	12, // 5: api.management.NetworkConfig.routes:type_name -> api.management.RouteConfig
	2,  // 6: api.management.PeerUpdate.type:type_name -> api.management.PeerUpdateType
	15, // 7: api.management.PeerUpdate.peer:type_name -> api.management.PeerInfo
	0,  // 8: api.management.PeerInfo.nat_type:type_name -> api.management.NATType
	3,  // 9: api.management.ManagementService.Register:input_type -> api.management.RegisterRequest
	6,  // 10: api.management.ManagementService.Heartbeat:input_type -> api.management.HeartbeatRequest
	10, // 11: api.management.ManagementService.GetNetworkConfig:input_type -> api.management.GetNetworkConfigRequest
	13, // 12: api.management.ManagementService.SyncPeers:input_type -> api.management.SyncPeersRequest
	5,  // 13: api.management.ManagementService.Register:output_type -> api.management.RegisterResponse
	8,  // 14: api.management.ManagementService.Heartbeat:output_type -> api.management.HeartbeatResponse
	11, // 15: api.management.ManagementService.GetNetworkConfig:output_type -> api.management.NetworkConfig
	14, // 16: api.management.ManagementService.SyncPeers:output_type -> api.management.PeerUpdate
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_management_proto_init() }
func file_api_proto_management_proto_init() {
	if File_api_proto_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_management_proto_rawDesc), len(file_api_proto_management_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_management_proto_goTypes,
		DependencyIndexes: file_api_proto_management_proto_depIdxs,
		EnumInfos:         file_api_proto_management_proto_enumTypes,
		MessageInfos:      file_api_proto_management_proto_msgTypes,
	}.Build()
	File_api_proto_management_proto = out.File
	file_api_proto_management_proto_goTypes = nil
	file_api_proto_management_proto_depIdxs = nil
}
